/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hbfkwpgmajadnjqlnfhs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZmt3cGdtYWphZG5qcWxuZmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5ODc5NDksImV4cCI6MjA3NzU2Mzk0OX0.TxASlnoV3-W3aHa7eyG7PJJKf6-CWYqV6Yr_1FyhRac"